config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    resources :users,only: [:index,:show,:edit,:update,:destroy]
  end

  namespace :admin do
    resources :posts,only: [:index,:show,:edit,:update,:destroy]

  end
  namespace :admin do
    get 'homes/top'
  end


  # ユーザー用
# URL /customers/sign_in ..
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  get 'about' => 'public/homes#about'
  root 'public/homes#top'
 scope module: :public do
    resources :posts,only: [:index,:new,:create,:show,:edit,:update,:destroy]

    resources :packings,only: [:index,:new,:create,:show,:edit,:update,:destroy]

    resources :schedules,only: [:index,:new,:create,:show,:edit,:update,:destroy]

    resources :users,only: [:show,:edit,:update,:destroy]

    get 'users/unsubscribe'
    get 'users/withdraw'

    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    get 'search/search'

 end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, presence: true
  validates :nickname_kana, presence: true
  validates :phone_number, presence: true
  validates :email, uniqueness: true


  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
     @users = User.all.page(params[:page]).per(10)

  end

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to admin_user_path
    else
      render 'edit'
    end
  end

private
   def user_params
     params.require(:user).permit(
       :nickname,:nickname_kana,:phone_number,:email,:is_deleted)
   end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
   <table class="table">
      <thead>
        <tr>
            <th>会員ID</th>
            <th>ニックネーム</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% users.each do |user| %>
         <tr>
             <td class="info col-xs-1">
                <%= user.id %>
             </td>
             <td class="text-left">
                <%= link_to user.nickname, admin_users_edit_path %>
             </td>
             <td class="text-left">
                <%= user.email %>
             </td>
             <td class="col-xs-2">
                <% if user.is_deleted == true %>
                  <p class="text-secondary">退会済</p>
                <% else %>
                  <p class="text-success">有効</p>
                <% end %>
             </td>
         </tr>
        <% end %>
      </tbody>
    </table>

app/views/admin/users/edit.html.erb
<% provide(:title, "ユーザー情報編集") %>
<div class="container">
  <h2 class="text-center m-5"><%= nickname(@user)%>さんの会員情報編集</h2>
  <div class="row d-flex justify-content-center">

  <%= form_with model: @user, url: admin_user_path, local: true do |f| %>
    <div class="col-xs-10 offset-1">
      <div class="form-group col-xs-9">
        <%= f.label :"会員ID", class: "col-sm-4" %>
        <%= f.label :"#{@user.id}" %>
      </div>
      <div class="form-group col-xs-9">
        <%= f.label :"ニックネーム", class: "col-sm-4 control-label" %>
        <%= f.text_field :nickname, class: "col-sm-3 form-control-static" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"フリガナ", class: "col-sm-4 control-label" %>
        <%= f.text_field :nickname_kana, class: "col-sm-3 form-control-static name" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"電話番号", class: "col-sm-4 control-label" %>
        <%= f.text_field :phone_number, class: "col-sm-4" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"メールアドレス", class: "col-sm-4 control-label" %>
        <%= f.text_field :email, class: "col-sm-6" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"会員ステータス", class: "col-sm-4 control-label" %>
        　<%= f.radio_button :is_deleted, false %>
        　<%= f.label :is_deleted, "有効"%>
        　<%= f.radio_button :is_deleted, true %>
        　<%= f.label :is_deleted, "退会" %>
      </div>
    </div>
      <div class="form-group col-xs-9 d-flex justify-content-around">
        <%= f.submit '変更を保存する' ,class: "btn btn-success" %>
        <%= link_to '会員詳細画面へ戻る',admin_user_path, class:"btn btn-outline-secondary"%>
      </div>

  <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, "会員情報一覧") %>
<div class="container">
 <h2 class="my-5">会員一覧</h2>
  <div class="row d-flex justify-content-center">
  <%= render 'index', users: @users%>
 </div>
 <div class="d-flex justify-content-center"><%= paginate(@users)%></div>
</div>>

app/views/admin/users/show.html.erb
<% provide(:title, "ユーザー情報詳細") %>
<div class="container">
  <h2 class="mt-5 text-center"><%= nickname(@user)%>さんのユーザー詳細</h2>
    <div class="row m-5">
      <div class="col-10 offset-1">
          <table class="table">
            <tr>
              <th class="text-center">ユーザーID</th>
              <td><%= @user.id%></td>
            </tr>

            <tr>
              <th class="text-center">ニックネーム</th>
              <td><%= nickname(@user) %></td>
            </tr>

            <tr>
              <th class="text-center">フリガナ</th>
              <td><%= nickname_kana(@user)%></td>
            </tr>

            <tr>
              <th class="text-center">電話番号</th>
              <td><%= @user.phone_number%></td>
            </tr>

            <tr>
              <th class="text-center">メールアドレス</th>
              <td><%= @user.email%></td>
            </tr>
            <tr>
              <th class="text-center">会員ステータス</th>
              <% if @user.is_deleted == true%>
               <td class="text-secondary">退会済み</td>
              <% else %>
               <td class="text-success">有効</td>
              <% end %>
            </tr>
          </table>
          <div class="d-flex justify-content-around">
            <p><%= link_to "編集する",admin_users_edit_path, class:"btn btn-success"%></p>
            <p><%= link_to "投稿履歴一覧を見る",admin_posts_index_path, class:"btn btn-primary"%></p>
          </div>
   　　 </div>
  　</div>
 </div>