config/routes.rb
Rails.application.routes.draw do

# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    resources :users,only: [:index,:show,:edit,:update,:destroy]
  end

  namespace :admin do
    resources :posts,only: [:index,:show,:edit,:update,:destroy]

  end
  namespace :admin do
    get 'homes/top'
  end


  # ユーザー用
# URL /customers/sign_in ..
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  get 'about' => 'public/homes#about'
  root 'public/homes#top'
 scope module: :public do
    resources :posts,only: [:index,:new,:create,:show,:edit,:update,:destroy]

    resources :packings,only: [:index,:new,:create,:show,:edit,:update,:destroy]

    resources :schedules,only: [:index,:new,:create,:show,:edit,:update,:destroy]

    resources :users,only: [:show,:edit,:update,:destroy]

    get 'users/unsubscribe'
    get 'users/withdraw'

    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    get 'search/search'

 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   belongs_to :user
   belongs_to :post
end

app/models/packing.rb
class Packing < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, presence: true
  validates :nickname_kana, presence: true
  validates :phone_number, presence: true
  validates :email, uniqueness: true


  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
   before_action :authenticate_admin!
  def index
    @posts = Post.page(params[:page]).per(10)
  end

  def show
     @post = Post.find(params[:id])
  end

  def edit
    @Post = Post.find(params[:id])
  end

  def update
     @post = Post.find(params[:id])
     if @post.update(item_params)
       flash[:notice] = "投稿の変更が完了しました。"
       redirect_to admin_post_path(@post)
     else
       flash[:alert] = "投稿の変更内容に不備があります。"
       render :edit
     end
  end


  private
  def post_params
    params.require(:post).permit(:post_name,:caption)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
     @users = User.all.page(params[:page]).per(10)

  end

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to admin_user_path
    else
      render 'edit'
    end
  end

private
   def user_params
     params.require(:user).permit(
       :nickname,:nickname_kana,:phone_number,:email,:is_deleted)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
     private
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
         admin_homes_top_path
      else
        root_path
      end
    end

    def after_sign_out_path_for(resource_or_scope)
      if  resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :nickname, :nickname_kana,:phone_number])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
    end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
       <p class="text-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
       <p class="text-danger"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center">© 2023 06~ 女子一人旅のススメ</p>
  <div class="d-flex justify-content-center">
    <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-2x"></i></a>
    <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-2x"></i></a>
    <a href="#" class="mx-1 text-dark"><i class="far fa-envelope fa-2x"></i></a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
      <% if admin_signed_in? %>
        <%= link_to "(管理者)女子一人旅のススメ", admin_session_path, class:"header-title navbar-brand"%>
      <% else %>
        <%= link_to "女子一人旅のススメ", root_path, class:"header-title navbar-brand"%>
      <% end %>

      <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">

         <% if user_signed_in? %>


          <li class="nav-item">
            <%= link_to "Mypage", user_path(current_user), class: "btn btn-outline-secondary mx-3 my-1"%>
          </li>

          <li class="nav-item ">
            <i class="fa-solid fa-globe"></i>
            <%= link_to "About", about_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>

          <li class="nav-item">
            <%= link_to "投稿",new_post_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>

          <li class="nav-item">
            <%= link_to "投稿一覧",posts_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>

          <li class="nav-item">
            <%= link_to "Schedules", schedules_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>

          <li class="nav-item">
            <%= link_to "Packing", packings_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>

          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>

         <% elsif admin_signed_in? %>
           <li class="nav-item">
             <%= link_to "Home",   admin_homes_top_path,class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>

           <li class="nav-item">
             <%= link_to "ユーザー一覧", admin_users_path, class:'btn btn-outline-secondary mx-3 my-1'%>
           </li>

           <li class="nav-item">
             <%= link_to "投稿一覧", admin_posts_path, class:'btn btn-outline-secondary mx-3 my-1'%>
           </li>

           <li class="nav-item">
             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
         <% else %>

          <li class="nav-item">
            <%= link_to "Home", root_path, class: "btn btn-outline-secondary mx-3 my-1"%>
          </li>

          <li class="nav-item ">

            <%= link_to "About", about_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>

          <li class="nav-item">
            <%= link_to "投稿一覧",posts_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>


           <li class="nav-item">
             <%= link_to "新規登録", new_user_registration_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>

           <li class="nav-item">
             <%= link_to "ログイン", new_user_session_path,class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>

          <% end %>
        </ul>
      </div>

 </nav>
</header>

app/views/layouts/_search.html.erb
<%= form_with url: search_search_path, method: :get, local: true do |f| %>
  <div class="d-flex justify-content-end mt-3 mr-5">
    <%= f.text_field :content, placeholder: "\uf002 Search", class: "fa" %>
    <%= f.submit "検索", class:"btn btn-outline-secondary ml-2"%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>女子一人旅のススメ</title>
     <%= favicon_link_tag 'suitcase.jpeg' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/b4a646c6ff.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
    <%= render "layouts/header"%>
    <main>
    <% if user_signed_in?%>
      <%= render "layouts/search"%>
    <% end %>
      <div class="container">
      <div id="flash">
        <%= render "layouts/flash" %>
      </div>
    <%= yield %>
    </main>
  </body>
</html>